### ISSUE TITLE
game files for 'snap' version

### ISSUE THREAD

**Issue by demoth** [fredldotme/yamagi-quake2-snap#1]
Hi 
I have installed snap version (https://snapcraft.io/yamagi-quake2-beidl) on ubuntu 19.04
I did not find instruction how to configure snap version to use game files (steam)

I got the same error all the times: `Error: Couldn't load pics/colormap.pcx`
I tried the following:

- run from location where steam game is located ~/.steam/steam/steamapps/common/Quake 2/
- link game files to ~/snap/yamagi-quake2-beidl/40/.yq2/baseq2/
- create ~/.y2q/baseq2/ with links to packs

the steam version (3.20) runs fine (through steamplay, proton-4.6)

I think installation guide is missing the `snap` version hints.
If I got to run the game i can add PR to documentation

**Comment by fredldotme** [comment]
AFAIK AppArmor will deny access to the symlinked files due to the files residing in a hidden folder (.steam). What you could do instead is copy the files out. The GUI launcher usually asks you to select the right directory, you can test the sandbox' capability to read the game files this way.

**Comment by demoth** [comment]
@fredldotme 
copying game files to `~/snap/yamagi-quake2-beidl/40/.yq2/baseq2/` worked!

**Comment by fredldotme** [comment]
I think we can close this issue.
